### ISSUE TITLE
[User question] Usage

### ISSUE THREAD

**Issue by BtM909** [ishamf/brackets-standard#2]
Just a stupid question. I would like to "use" this extension in Brackets.

I assume it would show the errors similar to JSHint / JSLint. Is my assumption wrong? If yes (I know assumptions are the mother ....), how would it work? If no, is there anything I need to config (which defeats the porpose :)).

I've installed JS standard via NPM globally (Windows) and the command-line tool works.

**Comment by ishamf** [comment]
Yes, it should do that... You might need to [change your linter](https://stackoverflow.com/questions/27584301/adobe-brackets-disable-jslint-but-allow-jshint), then it would show errors on any `.js` file.

**Comment by BtM909** [comment]
I'm currently using

```
"language": {

    "javascript": {
        "linting.prefer": [
            "standard",
            "JSHint",
            "JSCS"
        ],
        "linting.usePreferredOnly": true
    }
}
```

(btw, it doesn't matter if I enable or disable JSHint and JSCS, since these aren't enabled in brackets)

For whatever reason after a few restarts (F5's) I actually get my first warning / error:

> standard terminated with error: {1}

The console shows this error:

> [CodeInspection] Provider standard (async) failed: undefined (/language/CodeInspection.js:278)

Any help is appreciated

**Comment by ishamf** [comment]
Hmm, I'll try to reproduce it. Can I see what other plugins you're using?

**Comment by ishamf** [comment]
Seems to be working on a fresh Brackets install.
(I haven't used Brackets for a few years, quite surprised my plugin still works lol)

![standardworking](https://cloud.githubusercontent.com/assets/3515649/16274318/4621d974-38cf-11e6-9e5c-6bfa4bc4fd91.PNG)

**Comment by mrsteele** [comment]
This issue is happening for me too. I have a fresh install of Brackets and no other plugins running.

**Comment by ishamf** [comment]
@mrsteele Do you have standard installed globally? Also, are there any errors on the console?

**Comment by mrsteele** [comment]
Yes.

```
Matts-MBP:~ msteele$ npm ls -g --depth=0
/usr/local/lib
├── gulp@3.9.0
├── mocha@2.5.3
├── npm@3.8.0
├── standard@7.1.2
└── yo@1.8.4
```

Console errors match closely to what @BtM909 mentioned.

```
ErrorNotification.js:125 [CodeInspection] Provider standard (async) failed: undefined
window.console.error @ ErrorNotification.js:125
```

**Comment by ishamf** [comment]
@mrsteele I see you're on a mac. That might have something to do with it, since I only tested this on windows.

Can you perform the steps described [here](https://github.com/adobe/brackets/wiki/Brackets-Node-Process:-Overview-for-Developers#standard-debugging) and see if there are any error messages in the node process?

**Comment by mrsteele** [comment]
Okay, debugging is showing everything and nothing...

Looks like it is hitting a "commandError" in `NodeConnection._receive` from the `/utils/NodeConnection.js` file.

```
{
    "type":"commandError",
    "message": {
        "id":3,
        "message": {
            "killed":false,
            "code":127,
            "signal":null
        }
    }
}
```

I'll dig a little more and see if I can help.

**Comment by mrsteele** [comment]
The errors I am getting back or turning up nothing... cannot figure out what is going on.

**Comment by constagorgan** [comment]
I had the exact same problem. I tried everything (deleting other linters, opening other projects, various configurations in brackets.json, reinstalling Brackets, reinstalling "standard" locally/globally, reinstalling the extension, etc.).

Installing another version of "standard" solved it for me.

The default "standard" version installed by npm at this time is **8.5.0**. So I installed an older version of it which is **7.1.2**. And kaboom it worked!

Tips for other ppl that might encounter this problem:
Check if you have "standard" installed globally:

```
npm ls -g --depth=0
```

if it is, uninstall it

```
npm uninstall -g standard
```

and install this version: **7.1.2**

```
npm install -g standard@7.1.2
```

if it's not, just install that version

If the problem persists try a fresh install of Brackets and the Standard Code Style extension.

Extra tip:
If you wish to see only the "standard" linter output in the console add this to the brackets.json file (you can find it in the menu: Debug > Open Preferences File):

```
"language": {
  "javascript": {
    "linting.prefer": ["standard"],
    "linting.usePreferredOnly": true
  }
}
```

**Comment by BtM909** [comment]
@constagorgan, this is *the* solution.... For now. Thanks, because this helps me to stay with Brackets :)

@ishamf, would this help you a little bit more to investigate?

**Comment by ishamf** [comment]
@BtM909 

Sorry, I no longer use Brackets, I switched to Atom about a year ago...

If anyone wants to take over the repo and brackets package I would be happy to give it away. 
Although it might be better to just rewrite it, the code is a bit messy, and it's just a few hundred lines of JS.

Alternatively, you can use this plugin https://github.com/zaggino/brackets-eslint and use the standardjs config https://github.com/feross/eslint-config-standard .
