### ISSUE TITLE
# standard terminated with error: {1}, Bracket's builtin runtime does not support es6 syntax

### ISSUE THREAD

**Issue by AxolotlxWando** [ishamf/brackets-standard#3]
Hi Brother, 
This might actually be Bracket's problem, or might be something to do with just my environment. But on my machine I have v6.5.0 nodejs however Bracket seemed to come with a v0.10.24 version which obviously does not support es6 backticks syntax causing this error.

I'm on a fedora 24 machine. Tracking down the executables I could see that brackets uses it's own node runtime
/usr/bin/brackets => /usr/lib64/brackets => which in turns is run by this: **/usr/lib64/Bracket-node**
Which seemed to be a builtin node runtime.

It was a easy fix for me, I just symbolic linked it to use my own runtime but I'm curious:
1. If the plugin must be coupled with bracket's builtin runtime.
2. Is the really old builtin runtime just me and my setup or it indeed ships with all installs.

```
/home/wando/.nvm/versions/node/v6.5.0/lib/node_modules/standard/node_modules/standard-engine/bin/cmd.js:48

    console.log(`
                ^
SyntaxError: Unexpected token ILLEGAL
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3
```

**Comment by chimmelb** [comment]
I get the same error when I just installed to brackets.
![image](https://cloud.githubusercontent.com/assets/5881179/21438662/31f82c64-c858-11e6-9f87-bfacde519338.png)
I don't think I'm using any es6 specific stuff here, just a little sample project.

**Comment by vaidd4** [comment]
Same error here with Windows 10 and brackets 1.8.0-17108 with a simple file and the following code : 
```
function say_hello(s) {
  alert("Hello", s)
}
```

**Comment by ghost** [comment]
I got a workaround that worked for me on this issue.

You need to make `standard` dependency available in the current directory too. In this case, use Node.js' `npm`.

Go to your current working directory, and run `npm install standard --save`. You may need package.json to ignore global variables and to add extra customizations.

Then you can open the directory and lint with brackets-standard just fine.

**Comment by feross** [comment]
Closing because it sounds like @momozor has a working solution :)
