### ISSUE TITLE
Archive repository

### ISSUE THREAD

**Issue by sonicdoe** [ishamf/brackets-standard#6]
Since this repository is no longer maintained, it could be [archived](https://help.github.com/en/articles/archiving-repositories) to make its maintenance status easier to spot.

**Comment by feross** [comment]
Thanks for the suggestion. I will add a note that this repo is looking for a maintainer

**Comment by sibiraj-s** [comment]
Brackets is set to say GoodBye on [Sept-2021](https://blog.brackets.io/brackets-eol-notice/). The project can be archived or may be fix it for one last time to work with whatever brackets out there and then archive it?
